import json
import sys
import unittest
from pathlib import Path
from urllib.parse import quote

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from services.douyin_browser import _captions_from_render, _pick_media, _urls_from_render


class DouyinPickMediaTests(unittest.TestCase):
    def test_render_prefers_matching_aweme_id(self):
        data = {
            "feed": [
                {"awemeId": "111", "src": "https://v26-web.douyinvod.com/wrong.mp4"},
                {"awemeId": "222", "src": "https://v26-web.douyinvod.com/right.mp4"},
            ]
        }
        encoded = quote(json.dumps(data, ensure_ascii=False))
        urls = _urls_from_render(encoded, "222")
        self.assertEqual(urls, ["https://v26-web.douyinvod.com/right.mp4"])

    def test_pick_media_uses_main_player_first(self):
        snapshot = {
            "mainSrc": "https://v26-web.douyinvod.com/main.mp4",
            "renderText": "",
        }
        captured = ["https://v26-web.douyinvod.com/other.mp4"]
        urls = _pick_media(captured, snapshot, "123")
        self.assertEqual(urls[0], "https://v26-web.douyinvod.com/main.mp4")

    def test_render_extracts_cla_caption_track(self):
        data = {
            "awemeId": "222",
            "claInfo": {
                "captionInfos": [
                    {
                        "url": "https://sf3-cdn-tos.douyinstatic.com/obj/ies-hotsoon-caption/a.vtt",
                        "languageCode": "zh-CN",
                        "captionFormat": "webvtt",
                        "isAutoGenerated": True,
                    }
                ]
            },
        }
        encoded = quote(json.dumps(data, ensure_ascii=False))
        tracks = _captions_from_render(encoded, "222")
        self.assertEqual(len(tracks), 1)
        self.assertEqual(tracks[0]["lang"], "zh-CN")
        self.assertEqual(tracks[0]["source"], "auto")
        self.assertIn(".vtt", tracks[0]["fmt"]["url"])

    def test_render_uses_inline_caption_content(self):
        data = {
            "aweme_id": "333",
            "cla_info": {
                "caption_infos": [
                    {
                        "caption_content": "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\n你好",
                        "language_code": "zh",
                        "caption_format": "webvtt",
                    }
                ]
            },
        }
        encoded = quote(json.dumps(data, ensure_ascii=False))
        tracks = _captions_from_render(encoded, "333")
        self.assertEqual(tracks[0]["source"], "official")
        self.assertIn("你好", tracks[0]["fmt"]["data"])


if __name__ == "__main__":
    unittest.main()
